:-use_module(engine/katia_engine).

parent(kateryna_t,kateryna_k).
parent(teodor_t,kateryna_k).
parent(teodor_t,muxajlo).
parent(kateryna_t,muxajlo).
parent(muxajlo,marjan).
parent(olga_o,marjan).
parent(olga_o,marjan).
parent(marjan,oles).
parent(marjan,roman).
parent(olga_s,oles).
parent(olga_s,roman).
parent(roman,zahar).
parent(roman,oleg).
parent(galja_s,zahar).
parent(galja_s,oleg).
parent(muxajlo,volodumura_o).
parent(jarko,oleg_o).
parent(jarko,bogdan_o).
parent(volodumura_o,oleg_o).
parent(volodumura_o,bogdan_o).
parent(olga_o,volodumura_o).
parent(volodumur,stefania_s).
parent(volodumur,muroslava).
parent(volodumur,roman_s).
parent(kateryna_k,stefania_s).
parent(kateryna_k,muroslava).
parent(kateryna_k,roman_s).
parent(bogdan,galyna).
parent(jaroslav_pl,andrji_pl).
parent(jaroslav_pl,slava).
parent(stefa_pl,andrji_pl).
parent(stefa_pl,slava).
parent(slava,xrystynka).
parent(endrjy,xrystynka).
parent(olenka,stanislav).
parent(olenka,maja).
parent(andrji_pl,stanislav).
parent(andrji_pl,maja).
parent(svjat,jaroslav_pl).
parent(svjat,bogdan).
parent(ljana,bogdan).
parent(ljana,jaroslav_pl).
parent(stefania_s,igor).
parent(bogdan,igor).
parent(ivan,iryna).
parent(ivan,eva).
parent(eva,liza).
parent(ivan,stefania_r).
parent(maria_m,iryna).
parent(maria_m,eva).
parent(maria_m,stefania_r).
parent(stefania_r,galuna_r).
parent(stefania_r,bogdan_r).
parent(grugorij,galuna_r).
parent(grugorij,bogdan_r).
parent(iryna,yura).
parent(vasul,jaroslav).
parent(sofia,anna).
parent(sofia,antonina).
parent(sofia,stefka_b).
parent(andrij_b,anna).
parent(andrij_b,antonina).
parent(andrij_b,stefka_b).
parent(antonina,lesja).
parent(antonina,mixal).
parent(anna,jaroslav).
parent(vasul,maria_b).
parent(anna,maria_b).
parent(vasul,olga).
parent(anna,olga).
parent(olga,galja).
parent(olga,jarko_k).
parent(olga,andrji_k).
parent(misha,jarko_k).
parent(misha,andrji_k).
parent(andriji_k,sofia_k).
parent(tamara,sofia_k).
parent(galja,solomia).
parent(misha,galja).
parent(roman_m,solomia).
parent(anton,vasul).
parent(anton,tomash).
parent(romanna,tomash).
parent(romanna,vasul).
parent(tomash,levko).
parent(tomash,stefa).
parent(orusja,levko).
parent(orusja,stefa).
parent(maria_b,tereza).
parent(petro,tereza).
parent(tereza,oksana).
parent(tereza,petro_p).
parent(petro_p,andriji_p).
parent(petro_p,maria_p).
parent(oksana_p,maria_p).
parent(oksana_p,andriji_p).
parent(bogdan_p,oksana).
parent(bogdan_p,petro_p).
parent(oksana,markijan).
parent(oksana,yustyna).
parent(pavlo_p,markijan).
parent(pavlo_p,yustyna).
parent(jaroslav,yura).
parent(iryna,orest).
parent(jaroslav,orest).
parent(orest,pavlo).
parent(natalia,pavlo).
parent(orest,ostap).
parent(orest,xrystja_b).
parent(natalia,xrystja_b).
parent(natalia,ostap).
parent(galyna,kateryna_bugai).
parent(muroslava,maria_s).
parent(muroslava,nadia).
parent(nadia,nelja).
parent(nadia,teodor).
parent(oleksandr,nelja).
parent(oleksandr,teodor).
parent(bogdan_s,maria).
parent(bogdan_s,nadia).
parent(yura,kateryna_bugai).
parent(galyna,taras).
parent(yura,taras).
parent(stefania_s,galyna).
pair(galyna,yura).
pair(natalia,orest).
pair(nadia,oleksandr).
pair(muroslava,bogdan_s).
pair(stefania_s,bogdan).
pair(iryna,jaroslav).
pair(kateryna_t,teodor_t).
pair(kateryna_k,volodumur).
pair(olga_o,muxajlo).
pair(olga_s,marjan).
pair(galja_s,roman).
pair(volodumura_o,jarko).
pair(romanna,anton).
pair(orusja,tomash).
pair(anna,vasul).
pair(maria_b,petro).
pair(tereza,bogdan_p).
pair(oksana_p,petro_p).
pair(oksana,pavlo_p).
pair(stefania_r,grugorij).
pair(maria_m,ivan).
pair(olenka,andrji_pl).
pair(olga,misha).
pair(galja,roman_m).
pair(stefa_pl,jaroslav_pl).
pair(slava,endrjy).
pair(ljana,svjat).
pair(tamara,andriji_k).

female(kateryna_k).
female(kateryna_t).
female(olga_o).
female(galja_s).
female(volodumura_o).
female(muroslava).
female(stefania_s).
female(galyna).
female(iryna).
female(eva).
female(liza).
female(maria_m).
female(stefania_r).
female(galuna_r).
female(sofia).
female(anna).
female(antonina).
female(stefka_b).
female(lesja).
female(maria_b).
female(olga).
female(romanna).
female(stefa).
female(orusja).
female(tereza).
female(oksana).
female(xrystja_b).
female(natalia).
female(kateryna_bugai).
female(maria_s).
female(nadia).
female(nelja).
female(maria_p).
female(oksana_p).
female(yustuna).
female(sofia_k).
female(tamara).
female(slava).
female(ljana).
female(stefa_pl).
female(galja).
female(solomia).
female(maja).

male(teodor_t).
male(muxajlo).
male(marjan).
male(oles).
male(roman).
male(zahar).
male(oleg).
male(jarko).
male(oleg_o).
male(bogdan_o).
male(volodumur).
male(roman_s).
male(bogdan).
male(igor).
male(ivan).
male(grugorij).
male(bogdan_r).
male(vasul).
male(jaroslav).
male(yura).
male(andrij_b).
male(mixal).
male(anton).
male(tomash).
male(levko).
male(petro).
male(petro_p).
male(pavlo_p).
male(andriji_p).
male(bogdan_p).
male(markijan).
male(pavlo).
male(orest).
male(ostap).
male(teodor).
male(oleksandr).
male(bogdan_s).
male(jarko_k).
male(andrji_k).
male(taras).
male(svjat).
male(roman_m).
male(misha).
male(jaroslav_pl).
male(endrjy).
male(stanislav).